### PR TITLE
Build into subdirs of "build", make clean nukes "build"

### PR DESCRIPTION
**Pull request by rtjohnso**
Addresses #387 

Also, `make install` doesn't attempt to compile anything now.

### CODE REVIEW

**Comment by rtjohnso** [comment]
Apparently CI depends on binaries going into build/bin.

So this PR is incompatible w/ our current CI scripts.

**Comment by gapisback** [comment]
@rtjohnso - Let me look at this code this morning. I can fix the CI-scripts in your branch, and get something to work.
Will coordinate with you during our day.

**Comment by gapisback** [comment]
HI, @rtjohnso - I did not quite review your original `Makefile` changes, but extended on top of it, to add some testing machinery to verify that these `Makefile` changes still play well with each other.

You should be able to [cherry-pick this commit](https://github.com/vmware/splinterdb/commit/39e5d09f4339c92b8692ee3a31c5fde4b120abb8) from this branch, [robj/make-dirs3-apg-testMake-Sq](https://github.com/vmware/splinterdb/tree/robj/make-dirs3-apg-testMake-Sq).

I have not pushed this thru CI, but expect that it will work. For now, this testing machinery is not being invoked thru CI. You can manually test it out in your branch using:

```
RUN_MAKE_TESTS=true ./test.sh
```

**Review by gapisback — APPROVED** [review]
Reviewed these `Makefile` changes. They seem fine.

You need to cherry-pick the test-code changes and related fixes to `test.sh` provided separately in a branch off of this branch. See my note in the PR's comments chain.

Hopefully, once you pull that in, and make the required change to `Dockerfile`, your CI-jobs should succeed. 

Let me know when you have that extra fix ported. If CI still fails, will investigate.

**Pull request merged**
